/// <reference path="../../Scripts/core/gameManager.ts"/>
/// <reference path="../../Scripts/base/label.ts"/>
/// <reference path="../../Scripts/base/button.ts"/>
/// <reference path="../../Scripts/base/scene.ts"/>
/// <reference path="../../Scripts/base/gameobject.ts"/>
/// <reference path="../../Scripts/config/scene.ts"/>
/// <reference path="../../Scripts/config/tankTypes.ts"/>
/// <reference path="../../Scripts/scenes/over.ts"/>
/// <reference path="../../Scripts/scenes/play.ts"/>
/// <reference path="../../Scripts/scenes/start.ts"/>
/// <reference path="../../Scripts/objects/ocean.ts"/>
/// <reference path="../../Scripts/objects/plane.ts"/>
/// <reference path="../../Scripts/objects/island.ts"/>
/// <reference path="../../Scripts/objects/cloud.ts"/>
//# sourceMappingURL=_references.js.map